dependencies:
  build:
    - ruby:2.5.0

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu_ng:18.04
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
    commands:
      - gem install bundler -v 1.17.3
      - chmod +x yourbased.sh
      - ./yourbased.sh

ci:
  builds:
    - name: tests
      build_target: default

#trivial commit