# Note -- this requires the `file` utility... because paperclip
dependencies:
  build:
    - ruby:2.5.0

build_targets:
  - name: rails.master
    container: 
      image: yourbase/yb_ubuntu_ng_1:18.04
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
      - BUNDLE_GEMFILE=./gemfiles/Gemfile.rails.master
    commands:
      - gem install bundler -v 1.17.3 
      - bundle install -j4
      - bundle exec rspec
  - name: rails-5.0.1
    container: 
      image: yourbase/yb_ubuntu_ng_1:18.04
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
      - BUNDLE_GEMFILE=./gemfiles/Gemfile.rails.5.0.1
    commands:
      - gem install bundler -v 1.17.3 
      - bundle install -j4 
      - bundle exec rspec
  - name: rails-5.1.0
    container: 
      image: yourbase/yb_ubuntu_ng_1:18.04
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
      - BUNDLE_GEMFILE=./gemfiles/Gemfile.rails.5.1.0
    commands:
      - gem install bundler -v 1.17.3 
      - bundle install -j4 
      - bundle exec rspec
  - name: rails-5.2.0
    container: 
      image: yourbase/yb_ubuntu_ng_1:18.04
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
      - BUNDLE_GEMFILE=./gemfiles/Gemfile.rails.5.2.0
    commands:
      - gem install bundler -v 1.17.3 
      - bundle install -j4 
      - bundle exec rspec
ci:
  builds:
    - name: test-rails-5.0.1
      build_target: rails-5.0.1
    - name: test-rails-5.1.0
      build_target: rails-5.1.0
    - name: test-rails-5.2.0
      build_target: rails-5.2.0
    - name: test-rails-5.master
      build_target: rails.master
