dependencies:
  build:
    - ruby:2.5.0

build_targets:
  - name: default
    environment:
      - JRUBY_OPTS="-J-Xmx1024m --debug"
    commands:
      - gem install bundler -v 1.17.3
      - bundle install --gemfile ./gemfiles/Gemfile.rails.5.0.1
      - bundle exec rspec 
    tags:
     channel: experimental

ci:
  builds:
    - name: tests
      build_target: default

#trivial commit